---
title: "Ames Iowa House Prediction Project"
author: "Jordan Kassof and Jose Torres"
date: "2/11/2018"
output:
  pdf_document:
    toc: true
  rmdformats::readthedown:
    highlight: kate
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


***

# Introduction

Buying a house is one of the largest financial decisions many people will make. So many factors go into someone's decision, but it can be hard to really explain why one house "felt right" and another didn't. We want to quantify the factors that add up to someone making the decision to purchase a house.

# Data Description

We will be using the Ames, Iowa individual residential property sales data set freely available on Kaggle.com.  The dataset contains 2,930 observations with 79 explanatory variables. All observations occur between 2006 and 2010. Given the geography dependent nature of home value, the results of below analyses can't be applied nationally. For more information on the data, or to download it yourself, visit https://www.kaggle.com/c/house-prices-advanced-regression-techniques.

See the codebook.txt file in the github repo for complete information about all variables.

# Exploratory Analysis

Comments on various things noticed as exloring the data and general idea of what the cleaning was. Reference appendix for entire cleaninf functions and scripts.


# Questions of Interest

We focused on two approaches, one geared towards model performance and one towards model interpretability by a real estate agent.

## Interpretable Models

Restatement of problem here

### Model Selection

Type of Selection
Assumptions
Optional Comparing Competing Models

### Parameter Interpretation

Interpretation
Confidence Intervals


## Predictive Models

Restatement of problem here

### Model Selection

Type of Selection
Assumptions
Comparing Competing Models
    AIC, BIC, adj R2
    Interval CVPress
    External Cross Validation
    Kaggle Score
    
    
# Conclusion

# Appendix

